### PR TITLE
Implement completely new website

### LINKED ISSUE #1: Improve, Improve, Improve! :)
The website is still very poor. We should put much more information on it...
- [ ] List all "killer-features" of LibrePCB (with description and screenshots/videos).
- [ ] List import/export file formats
- [ ] Add FAQ
  - [ ] Why not contributing to KiCad?
  - [ ] Why should I use LibrePCB instead of KiCad?
- [ ] Add contact information
- [x] Add a "sponsors" section where we can put all logos of our sponsors.
- [ ] ~Add a Flattr donation button~
- [x] Add a Patreon donation button
- [x] Start writing a blog.

### LINKED ISSUE #7: Add Contact / Community Section
That would probably be useful.

### LINKED ISSUE #16: Roadmap
I think a rough roadmap (something like on the FOSDEM slides) would be great to have on the website.

### PR DESCRIPTION
**Pull request by ubruhin**
...finally!!! :smiley: 

Preview: https://librepcb.org/_branches/new-website/

Closes #1.
Closes #7.
Closes #16.
Replaces #37.

### CODE REVIEW

**Comment by dbrgn** [comment]
Very nice, turned out great! Some feedback:

- On the start page with the 8 features, I wouldn't link the entire section to the feature page. To me it wasn't clear that clicking on the text would lead to a page with more details. Instead, I would add a "More..." link to the end of each section that has a detail page.
- Similarly, for the sections "schematic editor", "board editor", etc I would probably add a button "learn more" below the GIFs. From just looking at the page (without actively hovering with the mouse over the GIF) it's not clear that clicking the GIF will lead to a different page.
- On the contact page, you list the e-mail "support at librepcb.org", but then say that people shouldn't use it to ask for support. Maybe you should change it to "hello@", "contact@" or something similar?
- On the license page, you have the sentence "Note that there is no free support available. For paid support, [contact us](https://librepcb.org/_branches/new-website/contact/).". Maybe clarify this as "there is no free support available from the project developers" and add "contact us or use community support" (with link to the forum)?
- On the download page, the download button for Linux is much larger and a different color than the buttons for Windows and macOS. Is there any reason for this? I'd make them the same.
- On the download page, I'd make the links to the Snap and Flatpak stores regular links. The buttons stand out way too much.

**Comment by ubruhin** [comment]
Thanks for the feedback! :tada: 

> On the start page with the 8 features, I wouldn't link the entire section to the feature page. To me it wasn't clear that clicking on the text would lead to a page with more details. Instead, I would add a "More..." link to the end of each section that has a detail page.

OK, I changed it to inline hyperlinks within the existing text (to keep the text short, instead of appending "More..."). Please let me know if you don't like that :see_no_evil: 

> Similarly, for the sections "schematic editor", "board editor", etc I would probably add a button "learn more" below the GIFs. From just looking at the page (without actively hovering with the mouse over the GIF) it's not clear that clicking the GIF will lead to a different page.

:heavy_check_mark: Replaced by buttons.

> On the contact page, you list the e-mail "support at librepcb.org", but then say that people shouldn't use it to ask for support. Maybe you should change it to "hello@", "contact@" or something similar?

:heavy_check_mark: Done!

> On the license page, you have the sentence "Note that there is no free support available. For paid support, [contact us](https://librepcb.org/_branches/new-website/contact/).". Maybe clarify this as "there is no free support available from the project developers" and add "contact us or use community support" (with link to the forum)?

:heavy_check_mark: Done!

> On the download page, the download button for Linux is much larger and a different color than the buttons for Windows and macOS. Is there any reason for this? I'd make them the same.

Sounds like your are using Linux, didn't disable JavaScript, and my OS detection script works :joy: The idea is to highlight the download button which is probably the one you're looking for.

> On the download page, I'd make the links to the Snap and Flatpak stores regular links. The buttons stand out way too much.

:heavy_check_mark: Done!

In addition, I changed the GIF overlays. There was a 1px progress bar at the button, but I didn't like it that much. Now I added a "clock" at the bottom right and an overlay as the last frame. The idea is to make clear when the loop starts/end but I am struggling a bit with *how* to make this clear...

**Comment by dbrgn** [comment]
> OK, I changed it to inline hyperlinks within the existing text (to keep the text short, instead of appending "More..."). Please let me know if you don't like that 🙈 

Works as well 🙂 

> Sounds like your are using Linux, didn't disable JavaScript, and my OS detection script works 😂 The idea is to highlight the download button which is probably the one you're looking for.

Ah, makes sense! In that case I'd reorder the sections though, so that your OS comes first. The enlarged button looks very inconsistent.

> In addition, I changed the GIF overlays. There was a 1px progress bar at the button, but I didn't like it that much. Now I added a "clock" at the bottom right and an overlay as the last frame. The idea is to make clear when the loop starts/end but I am struggling a bit with how to make this clear...

Nice, I never actually noticed those.

**Comment by ubruhin** [comment]
> Ah, makes sense! In that case I'd reorder the sections though, so that your OS comes first. The enlarged button looks very inconsistent.

I also had this idea but didn't implement it to reduce the effort -- since you now also mention this, I decided to implement it anyway and I love it! :smiley: 

So I think now everything should be finished :muscle:

**Pull request merged**
