### PR TITLE
Add blog post: LibrePCB 0.1.6 Released

### PR DESCRIPTION
**Pull request by ubruhin**
Preview is hosted here: https://librepcb.org/_branches/blogpost-release-0_1_6/blog/2021-10-31_release_0.1.6/

Note that the date of the post is provisional, not sure yet if this will be the release date...

@dbrgn would be nice if you can take a look at this :slightly_smiling_face:

### CODE REVIEW

**Comment by ubruhin** [comment]
Btw, I struggled a bit with adding two GIFs to a single blog post - somehow it is quite "noisy", but on the other hand, especially for these two topics, a GIF tells much more than the sentences... :thinking:

**Comment by dbrgn** [comment]
The GIFs are great 🙂

I read the draft this morning, and it looked good! Did you change anything since then?

**Comment by ubruhin** [comment]
> The GIFs are great slightly_smiling_face

:+1: :slightly_smiling_face: 

> I read the draft this morning, and it looked good! Did you change anything since then?

Yes, I rephrased some of the sentences a bit. But no changes to the changlog.

**Comment by dbrgn** [comment]
I re-read the longer sentences above the changelog, and it looks fine! 👍🏻

**Comment by ubruhin** [comment]
Perfect, thanks! :tada: So I'll merge this as soon as the release is created, probably within the next few days...

**Pull request merged**
