### PR TITLE
CSS improvements

### PR DESCRIPTION
**Pull request by dbrgn**
Make content left-aligned, improve spacing of headlines.

Before:

before

After:

after

### CODE REVIEW

**Comment by ubruhin** [comment]
I agree that the centered text is not ideal for the changelog, but IMHO it's even worse when just left-align everything. Especially the main page now looks ugly :(

**Comment by dbrgn** [comment]
I think it's *much* better when left-aligned than centered. The centered bullet list looks a bit strange, and nested lists aren't even possible.

**Comment by rnestler** [comment]
I like the left aligned much better! Centered bullet points just don't make any sense.

**Comment by ubruhin** [comment]
> The centered bullet list looks a bit strange, and nested lists aren't even possible.

> Centered bullet points just don't make any sense.

As I said, I agree regarding the bullet points. But look at the rest of the website:

Auswahl_011

Auswahl_012

Isn't this much uglier than the current (centered) website?

**Comment by dbrgn** [comment]
No. With very wide screens, most websites will limit the width of the page. A typical value was 960px, while many also use larger values like 1200px.

The reason why it looks a bit strange, is that the navigation is wider than the page body. That could be fixed (but it would probably be better to push the new website design instead).

**Comment by dbrgn** [comment]
Spacing on the download page seems to be a bit broken though :)

**Comment by ubruhin** [comment]
Since this is not ready yet (broken spacing on download page) and #63 fixes the issue as well, let's close this.

**Pull request closed without merging**
